dist: xenial
os: linux
language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
node_js:
- 14
jobs:
  include:
    - stage: test
      script:
        - yarn install
        - yarn test
    - stage: build
      script:
        - yarn install
        - yarn build
